### ISSUE TITLE
Feature request: Read age parameters form environment variables

### ISSUE THREAD

**Issue by pinpox** [histrio/age-secret.nvim#1]
Hello,

I have to encrypt to various, often changing public keys. It is a bit tedious to have to edit the neovim configuration every time or use the commands, especially if you want to script the editing.

Would it be possible to read the age key location and the recipients from environment variables if set? (falling back to the current behaviour)

**Comment by histrio** [comment]
Hi @pinpox! I'm glad I'm not the only one who found it useful.
Please try it with
```
use {
    'histrio/age-secret.nvim', branch = '1-feature-request-read-age-parameters-form-environment-variables' 
}
```

I'll merge it if the implementation is ok for you.
